spring:
  mail:
    #指定邮箱服务器地址
    host: smtp.qq.com
    #登录账号
    username: 516643429@qq.com
    #密钥
    password: hawtultqauqybgfg
    #端口
    port: 587
    #默认编码
    default-encoding: utf-8
    #使用的协议
    protocol: smtp
    #其他属性
    properties:
      "mail.smtp.timeout": 3000